### ISSUE TITLE
Notices: styling is broken on few pages

### ISSUE THREAD

**Issue by brbrr** [Automattic/vaultpress#22] opened 2019-06-14 09:23 UTC
"VaultPress needs your attention!" notice is a bit broken on few pages: 
- on Jetpack dashboard it looks completely broken, few not needed notice icons inside notice content? 
- on Jetpack Stats, the notice does not respect page horizontal padding   

<img width="1416" alt="Jetpack ‹ Testing Jetpack — WordPress 2019-06-14 11-36-27" src="https://user-images.githubusercontent.com/5654161/59498735-ab370f00-8e9e-11e9-883c-ff9af4082cb2.png">
<img width="1360" alt="Site Stats ‹ Testing Jetpack — WordPress 2019-06-14 11-41-21" src="https://user-images.githubusercontent.com/5654161/59498736-ab370f00-8e9e-11e9-893b-2e0a29b91ca8.png">

**Comment by jeherve** [comment] 2019-06-14 11:36
cc @eliorivero 	

Do you recall what version of Jetpack you were using at the time?

**Comment by eliorivero** [comment] 2019-06-14 17:26
@brbrr please test with latest master.

Now, this is a big concern since it will be released only with JP 7.5, unless we do a point release.

**Comment by jeherve** [comment] 2019-06-14 18:28
> unless we do a point release.

We'll do one on Monday and include your fix:
https://github.com/Automattic/jetpack/milestone/128

**Comment by jeherve** [comment] 2019-06-17 12:27
I can confirm that 7.4.1 solves the issue.

**Closed by jeherve** 2019-06-17 12:27 UTC
Labels: Admin Page, [Pri] BLOCKER, [Status] Needs Author Reply, [Type] Bug
